name: 现有游戏支持的反馈
description: BUG反馈，新功能请求，链接失效等等
title: "[反馈]: "
labels: ["exist"]
assignees:
  - qinlili23333
body:
  - type: markdown
    attributes:
      value: |
        请填写下列信息
  - type: dropdown
    id: type
    attributes:
      label: 选择类别
      options:
        - 优化工具
        - 平台移植
        - 游戏插件
        - 虚拟机整合包
        - 其他（不确定就选这个）
      multiple: false
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: 游戏名称
      description: 提供游戏的官方完整名称，请不要使用俗名或缩写，也尽可能不要使用非官方译名。
      placeholder: 例如：Apex Legends™
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: 存在问题的网页(如有)
      description: 如果问题出现在一个网页上，你可以提交链接
      placeholder: https://
    validations:
      required: false
  - type: textarea
    id: requirement
    attributes:
      label: 详细问题
      description: 写下你所遇到的问题或期望的需求
      placeholder: 不限字数随便写
      value: "我遇到了..."
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: 出现问题的设备
      description: 选择出现问题的设备
      multiple: false
      options:
        - Windows 10/11 X64
        - Windows 10/11 ARM64
        - Linux Desktop X64
        - Linux Desktop ARM64
        - Android
        - 其他拥有支持PWA的浏览器的设备
    validations:
      required: true
  - type: textarea
    id: talk
    attributes:
      label: 其他想写的
      description: 随便写，别把斗罗大陆贴进来就行
  - type: checkboxes
    id: terms
    attributes:
      label: 我同意...
      description: 提交后本反馈会公开展示，本反馈不包含任何隐私信息
      options:
        - label: 我已确认
          required: true
